apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: omnishop/auth-service:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: omnishop-config
            - secretRef:
                name: omnishop-secrets
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: omnishop-config
                  key: DB_HOST_AUTH
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: omnishop-config
                  key: AUTH_DB_URL
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - port: 8081
      targetPort: 8081
